### ISSUE TITLE
使用随机包名防止针对

### ISSUE THREAD

**Issue by RnJ4** [HiedaNaKan/FuckMFS#12]
若包名固定，检查者可以在安装取证工具前先通过adb pm uninstall，使这个程序无法正常工作

**Comment by HiedaNaKan** [comment]
@RnJ4 如果xposed的一个已经启用的模块被卸载，在卸载之后新安装其他应用这个模块会生效吗？

**Comment by RnJ4** [comment]
@HiedaNaKan  自己试了一下好像不行

**Comment by HiedaNaKan** [comment]
@RnJ4 那建议使用MT管理器 (bin.mt.cc) 修改包名安装 。

如果要在程序内自己实现，需要实现dex的反编译与回编译、axml与arsc的反编译与回编译、apk签名。

**Comment by HiedaNaKan** [comment]
@RnJ4 那建议使用Android应用MT管理器修改包名安装 。

如果要在程序内自己实现，需要实现dex的反编译与回编译、axml与arsc的反编译与回编译、apk签名。

**Comment by MlgmXyysd** [comment]
> 若包名固定，检查者可以在安装取证工具前先通过adb pm uninstall，使这个程序无法正常工作

摘自ZJDroid的方法，你可以把这个模块apk放到某个地方（比如/data/local/tmp），然后后缀名改成jar，最后在xp的modules.list里把apk改成jar路径就行了。

**Comment by MlgmXyysd** [comment]
https://github.com/halfkiss/ZjDroid
`该方式可以脱壳目前大部分流行的加固防护。(由于手机性能问题，运行较忙) 例外情况： 由于ApkProtect特定防修改检测，需要做如下修改即可解固该保护： （1）在设备上创建特定目录（如/data/local）并 chmod 为777 （2）复制zjdroid.apk到该目录，并修改文件名为zjdroid.jar (3) 修改/data/data/de.robv.android.xposed.installer/conf/modules.list 模块代码文件修改为"zjdroid.jar" 从启设备即可。`
