### ISSUE TITLE
联系人，短信，图库全部返回空值更让人怀疑

### ISSUE THREAD

**Issue by null4n** [HiedaNaKan/FuckMFS#3]
这样软件看到的就像一台全新的手机
建议增加让用户自己输入一些假的联系人信息让mfs读取，把短信里运营商和1066开头的短信给mfs读取，图库可以每日从bing每日图片里拉取，设置一个限额防止占用太多空间。这样看上去比较像日常使用的手机。
还有过滤mfs获取已安装软件，返回空值也明显有炸，考虑黑名单的包名过滤掉，其他的可以让它读取

**Comment by null4n** [comment]
毕竟如果都查手机了，这种软件要做的是让mfs扫描到的东西跟正常的普通手机没太大区别而不是直接不让它扫什么都返回空值

**Comment by HiedaNaKan** [comment]
那就自动生成联系人，返回1066的返回，图库的话要在线下载很麻烦，还不如直接返回空。

**Comment by HiedaNaKan** [comment]
已更新。对于短信联系人SIM卡号媒体文件应用列表不再返回0。

随机生成联系人、SIM卡信息。
对于非通知信息，随机修改号码与内容。
应用列表返回系统应用与国内白名单应用、去除签名检查。
音频、视频、相册全部返回随机生成的文件。
