### ISSUE TITLE
太极5.2 不支持

### ISSUE THREAD

**Issue by joket1999** [HiedaNaKan/FuckMFS#4]
![image](https://user-images.githubusercontent.com/6611880/60003878-2027f700-969e-11e9-86e5-11434caeacbd.png)

**Comment by HiedaNaKan** [comment]
您好，这是因为您的设备没有修改过adbd程序，通过adb连接手机安装apk无法直接安装到太极，所以太极智能提示了不支持哦。

**Comment by joket1999** [comment]
@HiedaNaKan 我是直接在手机下载安装的。那现在具体要怎么做呢？

**Comment by rhjdvsgsgks** [comment]
请阅读 [readme中“使用”的第二行](https://github.com/HiedaNaKan/FuckMFS#%E4%BD%BF%E7%94%A8)
