### ISSUE TITLE
太极兼容问题

### ISSUE THREAD

**Issue by Blankeer** [HiedaNaKan/FuckMFS#9]
以下来自 readme.md
```
## 太极

可笑 原来太极是白名单 还得给他某个死妈初中生他们发申请才能提示兼容 就不能给个 默认支持 的选项嘛 真是奇妙深刻 爱支持不支持 这么进步怎么买不起两台手机了 军训粪蛆有什么救的必要吗 就算本夜蝶的亲姐姐东风谷早苗碰到这种奇妙深刻的事也要心肺停止的罢 完美华丽 
```
谁告诉你太极适配是给初中生发申请的？
就不能看下太极官方说明，就开骂了？可笑
参见：
https://github.com/taichi-framework/TaiChi/issues/828
http://admin.taichi.cool/

**Comment by HiedaNaKan** [comment]
@Blankeer 您好，我说的是 他们，不是他。
